### ISSUE TITLE
TypeError: Blockchain.__init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by xX-MoonWalker-Xx** [pooriaahmadi/pennic#1]
Tried installing on windows

doesnt work...

```
E:\Coding\pennic-main>pipenv install
Creating a virtualenv for this project...
Pipfile: E:\Coding\pennic-main\Pipfile
Using C:/Python310/python.exe (3.10.3) to create virtualenv...
[ ===] Creating virtual environment...created virtual environment CPython3.10.3.final.0-64 in 5038ms
  creator CPython3Windows(dest=C:\Users\moonwalker\.virtualenvs\pennic-main-HTTcnDAe, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\moonwalker\AppData\Local\pypa\virtualenv)
    added seed packages: pip==22.2.2, setuptools==65.3.0, wheel==0.37.1
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Successfully created virtual environment!
Virtualenv location: C:\Users\moonwalker\.virtualenvs\pennic-main-HTTcnDAe
Pipfile.lock not found, creating...
Locking [packages] dependencies...
           Building requirements...
Resolving dependencies...
Success!
Locking [dev-packages] dependencies...
Updated Pipfile.lock (cd9484)!
Installing dependencies from Pipfile.lock (cd9484)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

E:\Coding\pennic-main>pipenv run generate_keys
'generate_keys' is not recognized as an internal or external command,
operable program or batch file.

E:\Coding\pennic-main>pipenv run generate_keys
'generate_keys' is not recognized as an internal or external command,
operable program or batch file.

E:\Coding\pennic-main>pipenv scripts
Command         Script
--------------  -------------------------------
generatekeys    python pennic/generate_keys.py
benchmark       python pennic/benchmark.py
example         python pennic/chain_example.py
setup_database  python pennic/setup_database.py
node            python pennic/node.py
mine            python pennic/mine.py

E:\Coding\pennic-main>pipenv run generatekeys
Traceback (most recent call last):
  File "E:\Coding\pennic-main\pennic\generate_keys.py", line 5, in <module>
    chain = Blockchain(os.getenv("BLOCKCHAIN_DATABASE_PATH"))
TypeError: Blockchain.__init__() takes 1 positional argument but 2 were given
```

also in the instructions. it is said to run generate_keys but there is no command such as that. guess thats a typo

**Comment by pooriaahmadi** [comment]
Hello,
1. The blockchain class has been fixed.
2. Yes, generate_keys was a typo, thanks for your attention
All problems have been fixed

**Comment by xX-MoonWalker-Xx** [comment]
Hi. tried the new version. this is the new error:
```
E:\Coding\pennic-main>pipenv run generatekeys
Traceback (most recent call last):
  File "E:\Coding\pennic-main\pennic\generate_keys.py", line 5, in <module>
    chain = Blockchain(os.getenv("BLOCKCHAIN_DATABASE_PATH"))
  File "E:\Coding\pennic-main\pennic\Blockchain\Blockchain.py", line 20, in __init__
    self.database.setup()
  File "E:\Coding\pennic-main\pennic\Database\Database.py", line 11, in setup
    self.connection = sqlite3.connect(self.path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by xX-MoonWalker-Xx** [comment]
i removed the last version completely. then after downloading the new version i ran these commands:
```
pipenv install 
pipenv scripts
pipenv generatekeys
```
 and got the error

**Comment by xX-MoonWalker-Xx** [comment]
is it a windows issue?

**Comment by pooriaahmadi** [comment]
$ touch .env
$ echo "HOST=localhost PORT=34756 BLOCKCHAIN_DATABASE_PATH=blockchain.db HASH_RATE=5500 DEVELOPMENT=1 RECENT_NODES_FILE_PATH=recent_nodes.json NODES_ASK_LIMIT=10" | tr " " "\n" >> .env
# Please replace HASH_RATE with the number in the benchmark command

**Comment by xX-MoonWalker-Xx** [comment]
oh okay. i tought the provided commands are in order

**Comment by pooriaahmadi** [comment]
yea sorry I no longer continue working on this project...
Also writing readme/documentation for any project is really hard

**Comment by xX-MoonWalker-Xx** [comment]
okay then. it worked but there are many more issues. like the setup_database wasn't following the blockchain inputs, i opened a pr for that  but after fixing that there are issues with the benchmark command.

this is a cool project btw! i will look into it when the issues are fixed
